[window]
decorations = "none"
dynamic_padding = true

[font]
size = 18

[env]
TERM = "xterm-256color"

[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'

[terminal.shell]
program = "/bin/zsh"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"

[[keyboard.bindings]]
key = "Return"
mods = "Control"
chars = "\u001b[13;5u"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
chars = "\u001b[13;6u"

[[keyboard.bindings]]
key = "A"
mods = "Control|Shift"
chars = "\u001b[65;6u"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
chars = "\u001b[66;6u"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
chars = "\u001b[67;6u"

[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
chars = "\u001b[68;6u"

[[keyboard.bindings]]
key = "E"
mods = "Control|Shift"
chars = "\u001b[69;6u"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
chars = "\u001b[70;6u"

[[keyboard.bindings]]
key = "G"
mods = "Control|Shift"
chars = "\u001b[71;6u"

[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
chars = "\u001b[72;6u"

[[keyboard.bindings]]
key = "I"
mods = "Control"
chars = "\u001b[105;5u"

[[keyboard.bindings]]
key = "I"
mods = "Control|Shift"
chars = "\u001b[73;6u"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u001b[74;6u"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
chars = "\u001b[75;6u"

[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[76;6u"

[[keyboard.bindings]]
key = "M"
mods = "Control|Shift"
chars = "\u001b[77;6u"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
chars = "\u001b[78;6u"

[[keyboard.bindings]]
key = "O"
mods = "Control|Shift"
chars = "\u001b[79;6u"

[[keyboard.bindings]]
key = "P"
mods = "Control|Shift"
chars = "\u001b[80;6u"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
chars = "\u001b[81;6u"

[[keyboard.bindings]]
key = "R"
mods = "Control|Shift"
chars = "\u001b[82;6u"

[[keyboard.bindings]]
key = "S"
mods = "Control|Shift"
chars = "\u001b[83;6u"

[[keyboard.bindings]]
key = "T"
mods = "Control|Shift"
chars = "\u001b[84;6u"

[[keyboard.bindings]]
key = "U"
mods = "Control|Shift"
chars = "\u001b[85;6u"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

# [[keyboard.bindings]]
# key = "C"
# mods = "Control"
# action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
chars = "\u001b[86;6u"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
chars = "\u001b[87;6u"

[[keyboard.bindings]]
key = "X"
mods = "Control|Shift"
chars = "\u001b[88;6u"

[[keyboard.bindings]]
key = "Y"
mods = "Control|Shift"
chars = "\u001b[89;6u"

[[keyboard.bindings]]
key = "Z"
mods = "Control|Shift"
chars = "\u001b[90;6u"

[[keyboard.bindings]]
key = "Key1"
mods = "Control|Shift"
chars = "\u001b[49;6u"

[[keyboard.bindings]]
key = "Key2"
mods = "Control|Shift"
chars = "\u001b[50;6u"

[[keyboard.bindings]]
key = "Key3"
mods = "Control|Shift"
chars = "\u001b[51;6u"

[[keyboard.bindings]]
key = "Key4"
mods = "Control|Shift"
chars = "\u001b[52;6u"

[[keyboard.bindings]]
key = "Key5"
mods = "Control|Shift"
chars = "\u001b[53;6u"

[[keyboard.bindings]]
key = "Key6"
mods = "Control|Shift"
chars = "\u001b[54;6u"

[[keyboard.bindings]]
key = "Key7"
mods = "Control|Shift"
chars = "\u001b[55;6u"

[[keyboard.bindings]]
key = "Key8"
mods = "Control|Shift"
chars = "\u001b[56;6u"

[[keyboard.bindings]]
key = "Key9"
mods = "Control|Shift"
chars = "\u001b[57;6u"

[[keyboard.bindings]]
key = "Key0"
mods = "Control|Shift"
chars = "\u001b[48;6u"

[[keyboard.bindings]]
key = "-"
mods = "Control|Shift"
chars = "\u001b[45;6u"

[[keyboard.bindings]]
key = "="
mods = "Control|Shift"
chars = "\u001b[61;6u"

[[keyboard.bindings]]
key = "LBracket"
mods = "Control|Shift"
chars = "\u001b[91;6u"

[[keyboard.bindings]]
key = "RBracket"
mods = "Control|Shift"
chars = "\u001b[93;6u"

[[keyboard.bindings]]
key = "\\"
mods = "Control|Shift"
chars = "\u001b[92;6u"

[[keyboard.bindings]]
key = ";"
mods = "Control|Shift"
chars = "\u001b[59;6u"

[[keyboard.bindings]]
key = "'"
mods = "Control|Shift"
chars = "\u001b[39;6u"

[[keyboard.bindings]]
key = ","
mods = "Control|Shift"
chars = "\u001b[44;6u"

[[keyboard.bindings]]
key = "."
mods = "Control|Shift"
chars = "\u001b[46;6u"

[[keyboard.bindings]]
key = "/"
mods = "Control|Shift"
chars = "\u001b[47;6u"
